M48
; DRILL file {KiCad 9.0.0} date 2025-03-13T21:04:02+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-13T21:04:02+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.900
%
G90
G05
T1
X149.0Y-45.0
T2
X136.0Y-53.0
X148.7Y-53.0
T3
X119.46Y-53.0
X122.0Y-53.0
M30
